// Usuarios Lipu Valle de México — auto-generados
export const LIVDM_USUARIOS = [
  { email: 's.esquivelh@traxion.global', password: 'Lipu100002', nombre: 'Serafin Esquivel Hernandez', rol: 'Jefe de Transportación', rolCode: 'JT', nomina: '15100002' },
  { email: 'pa.garcia@traxion.global', password: 'Lipu100006', nombre: 'Patricia Garcia Ramirez', rol: 'Coordinador', rolCode: 'C', nomina: '15100006' },
  { email: 'ca.flores@traxion.global', password: 'Lipu100008', nombre: 'Maria Del Carmen Del Rosario Flores Cardenas', rol: 'Ejecutivo', rolCode: 'C', nomina: '15100008' },
  { email: 'alejandroparra76938@gmail.com', password: 'Lipu100038', nombre: 'Alejandro Parra Diaz', rol: 'Coordinador', rolCode: 'C', nomina: '15100038' },
  { email: 'raulin1648@gmail.com', password: 'Lipu100044', nombre: 'Raul Hernandez Lopez', rol: 'Coordinador', rolCode: 'C', nomina: '15100044' },
  { email: 'raulfelix2630@gmail.com', password: 'Lipu100072', nombre: 'Raul Felix Noyola', rol: 'Delegado Sindical', rolCode: 'C', nomina: '15100072' },
  { email: 's.veloz@lipu.com', password: 'Lipu100089', nombre: 'Sabas Veloz Resendiz', rol: 'Coordinador', rolCode: 'C', nomina: '15100089' },
  { email: 'carloscruz1208@hotmail.com', password: 'Lipu100104', nombre: 'Juan Carlos Cruz Villanueva', rol: 'Coordinador', rolCode: 'C', nomina: '15100104' },
  { email: 'j.emmanuel.guerrero.m@gmail.com', password: 'Lipu100139', nombre: 'Juan Emmanuel Guerrero Marquez', rol: 'Coordinador', rolCode: 'C', nomina: '15100139' },
  { email: 'a.vargasr@traxion.global', password: 'Lipu100180', nombre: 'Aldo Elier Vargas Ramirez', rol: 'Jefe de Transportación', rolCode: 'JT', nomina: '15100180' },
  { email: 'olmedoricardo156@gmail.com', password: 'Lipu100205', nombre: 'Ricardo Olmedo Cruz', rol: 'Coordinador', rolCode: 'C', nomina: '15100205' },
  { email: 'dejesushdez09@gmail.com', password: 'Lipu100211', nombre: 'Antonio De Jesus Hernandez Miranda', rol: 'Coordinador', rolCode: 'C', nomina: '15100211' },
  { email: 'edgarlop8206@gmail.com', password: 'Lipu100244', nombre: 'Edgar Jorge Cruz Lopez', rol: 'Coordinador', rolCode: 'C', nomina: '15100244' },
  { email: 'hipolitorosas6548@gmail.com', password: 'Lipu100262', nombre: 'Hipolito Rosas Perez', rol: 'Coordinador', rolCode: 'C', nomina: '15100262' },
  { email: 's.acevedob@traxion.global', password: 'Lipu100298', nombre: 'Sayra Cristela Acevedo Bustamante', rol: 'Ejecutivo', rolCode: 'C', nomina: '15100298' },
  { email: 'sindicatolvm@lipu.com.mx', password: 'Lipu100309', nombre: 'Rafael Trejo Jimenez', rol: 'Delegado Sindical', rolCode: 'C', nomina: '15100309' },
  { email: 'j.tejeda@traxion.global', password: 'Lipu100324', nombre: 'Jonathan Tejeda Rodriguez', rol: 'Director', rolCode: 'ADMIN', nomina: '15100324' },
  { email: 'a.lopezc@traxion.global', password: 'Lipu100447', nombre: 'Alma Johana Lopez Cabello', rol: 'Jefe de Transportación', rolCode: 'JT', nomina: '15100447' },
  { email: 'sg6803771@gmail.com', password: 'Lipu103034', nombre: 'Sebastian Gutierrez Aparicio', rol: 'Coordinador', rolCode: 'C', nomina: '15103034' },
  { email: 'n.ramirezs@traxion.global', password: 'Lipu103143', nombre: 'Nestor Ramirez Santos', rol: 'Coordinador', rolCode: 'C', nomina: '15103143' },
  { email: 'polotrejo.c@gmail.com', password: 'Lipu104457', nombre: 'Hipolito Trejo Cortes', rol: 'Coordinador', rolCode: 'C', nomina: '15104457' },
  { email: 'jefe.combustible@traxion.global', password: 'Lipu104802', nombre: 'Omar Rodrigo Cruz Cruces', rol: 'Jefe de Transportación', rolCode: 'JT', nomina: '15104802' },
  { email: 'j.reyesp@traxion.global', password: 'Lipu108004', nombre: 'Jorge Reyes Pichardo', rol: 'Coordinador', rolCode: 'C', nomina: '15108004' },
  { email: 'b.segura@traxion.global', password: 'Lipu108093', nombre: 'Gicela Berenice Segura Salgado', rol: 'Subdirector', rolCode: 'ADMIN', nomina: '15108093' },
  { email: 'jefaturalvm1@traxion.global', password: 'Lipu110001', nombre: 'Jose Ivan Morales Aragon', rol: 'Jefe de Transportación', rolCode: 'JT', nomina: '15110001' },
  { email: 'estrellas19902011@hotmail.com', password: 'Lipu110638', nombre: 'Yazmin Rebeca Bucio Miranda', rol: 'Delegado Sindical', rolCode: 'C', nomina: '15110638' },
  { email: 'je.martinezg@traxion.global', password: 'Lipu111059', nombre: 'Jessica Nayelli Martinez Granados', rol: 'Ejecutivo', rolCode: 'C', nomina: '15111059' },
  { email: 'omarhernandez4785@gmail.com', password: 'Lipu111281', nombre: 'Omar Hernandez Hernandez', rol: 'Coordinador', rolCode: 'C', nomina: '15111281' },
  { email: 'c.manzano@lipu.com.mx', password: 'Lipu112258', nombre: 'Clara Manzano Quijano', rol: 'Gerente', rolCode: 'JT', nomina: '15112258' },
  { email: 'm.rodriguezg@traxion.global', password: 'Lipu112259', nombre: 'Ma. Perla Rodriguez Gonzalez', rol: 'Ejecutivo', rolCode: 'C', nomina: '15112259' },
  { email: 'v.vidal@traxion.global', password: 'Lipu112689', nombre: 'Veronica Adglahe Vidal Rios', rol: 'Ejecutivo', rolCode: 'C', nomina: '15112689' },
  { email: 'm.vanegas@lidcorp.mx', password: 'Lipu114464', nombre: 'Mauricio Vanegas Lomeli', rol: 'Director', rolCode: 'ADMIN', nomina: '15114464' },
  { email: 'julioarmandovazquezmartinez@gmail.com', password: 'Lipu114850', nombre: 'Julio Armando Vazquez Martinez', rol: 'Coordinador', rolCode: 'C', nomina: '15114850' },
  { email: 'hohm971226160@traxion.cloud', password: 'Lipu115061', nombre: 'Miguel Angel Horta Hernandez', rol: 'Coordinador', rolCode: 'C', nomina: '15115061' },
  { email: 'e.sanchezg@traxion.global', password: 'Lipu115069', nombre: 'Efrain Sanchez Garcia', rol: 'Jefe de Transportación', rolCode: 'JT', nomina: '15115069' },
  { email: 'e.navarrete@traxion.global', password: 'Lipu115365', nombre: 'Ever Jacob Navarrete Martinez', rol: 'Jefe de Transportación', rolCode: 'JT', nomina: '15115365' },
  { email: 'almacen.lvmx@lidcorp.mx', password: 'Lipu115366', nombre: 'Daniel Ramirez Garcia', rol: 'Coordinador', rolCode: 'C', nomina: '15115366' },
  { email: 'administracion.lvm@traxion.global', password: 'Lipu116287', nombre: 'Isaha Salem Boguett Franco', rol: 'Coordinador', rolCode: 'C', nomina: '15116287' },
  { email: 'aamc840521sf3@traxion.cloud', password: 'Lipu117078', nombre: 'Claudia Ivon Alvarado Mora', rol: 'Coordinador', rolCode: 'C', nomina: '15117078' },
  { email: 'aema841109ay9@traxion.cloud', password: 'Lipu117956', nombre: 'Antonio Aveldaño Marin', rol: 'Coordinador', rolCode: 'C', nomina: '15117956' },
  { email: 'gocb9307232l1@traxion.cloud', password: 'Lipu118326', nombre: 'Brandon Salvador Gomez Cornejo', rol: 'Coordinador', rolCode: 'C', nomina: '15118326' },
  { email: 'r.grego@traxion.global', password: 'Lipu118355', nombre: 'Rafael Grego Kibrit', rol: 'Director Regional', rolCode: 'ADMIN', nomina: '15118355' },
  { email: 'jalfred.jz@gmail.com', password: 'Lipu118473', nombre: 'Jose Alfredo Zurita Hernandez', rol: 'Coordinador', rolCode: 'C', nomina: '15118473' },
  { email: 'al.garciac@traxion.global', password: 'Lipu118778', nombre: 'Aline Sarai Garcia Cerriteño', rol: 'Jefe de Transportación', rolCode: 'JT', nomina: '15118778' },
  { email: 'reclutamiento3@traxion.global', password: 'Lipu119197', nombre: 'Daniela Flores Flores', rol: 'Coordinador', rolCode: 'C', nomina: '15119197' },
  { email: 'a.garciaf@traxion.global', password: 'Lipu119262', nombre: 'Ana Laura Garcia Flores', rol: 'Ejecutivo', rolCode: 'C', nomina: '15119262' },
  { email: 'l.ordonezm@traxion.global', password: 'Lipu119391', nombre: 'Lorena Ordoñez Mendez', rol: 'Ejecutivo', rolCode: 'C', nomina: '15119391' },
  { email: 'a.barceloa@traxion.global', password: 'Lipu120185', nombre: 'Amanda Barcelo Amaro', rol: 'Jefe de Transportación', rolCode: 'JT', nomina: '15120185' },
  { email: 'l.nerion@traxion.global', password: 'Lipu120642', nombre: 'Lilian Marlene Nerio Nerio', rol: 'Gerente', rolCode: 'JT', nomina: '15120642' },
  { email: 'aezd881230g70@traxion.cloud', password: 'Lipu121112', nombre: 'David Ameca Zarazas', rol: 'Coordinador', rolCode: 'C', nomina: '15121112' },
  { email: 'e.cervantesr@traxion.global', password: 'Lipu121179', nombre: 'Estefania Cervantes Ramos', rol: 'Ejecutivo', rolCode: 'C', nomina: '15121179' },
  { email: 'nanaspeterson@traxion.global', password: 'Lipu121191', nombre: 'Ma. De Jesus Angelica Montoya Rojo', rol: 'Coordinador', rolCode: 'C', nomina: '15121191' },
  { email: 'cordinador@traxion.global', password: 'Lipu121306', nombre: 'Sergio Humberto Hernandez Vera', rol: 'Coordinador', rolCode: 'C', nomina: '15121306' },
  { email: 'f.arzate@traxion.global', password: 'Lipu121580', nombre: 'Francisco Heriberto Arzate Hernandez', rol: 'Gerente', rolCode: 'JT', nomina: '15121580' },
  { email: 'madd9204161d0@traxion.cloud', password: 'Lipu122042', nombre: 'Daniela Martinez Dominguez', rol: 'Coordinador', rolCode: 'C', nomina: '15122042' },
  { email: 'ialj960810kn4@traxion.cloud', password: 'Lipu122328', nombre: 'Jessica Amahyrani Ibañez Lazcano', rol: 'Jefe de Transportación', rolCode: 'JT', nomina: '15122328' },
  { email: 'eusa730708d98@traxion.cloud', password: 'Lipu122667', nombre: 'Jose Antonio Esqueda Sanchez', rol: 'Coordinador', rolCode: 'C', nomina: '15122667' },
]